# Generated by Django 4.2.13 on 2024-05-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kotani', '0009_alter_goods_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='Локальный'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Kotani.measure', verbose_name='Единица измерения'),
        ),
    ]
