# Generated by Django 4.2.13 on 2024-05-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kotani', '0010_alter_goods_is_local_alter_goods_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
