# Generated by Django 4.2.13 on 2024-05-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kotani', '0011_alter_goods_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipegoods',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_goods', to='Kotani.recipes', verbose_name='Рецепт'),
        ),
    ]
