# Generated by Django 4.2.13 on 2024-05-28 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gusto', '0002_alter_familygoodsinstock_change_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='icon_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familyrecipes',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='familyrecipes',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods',
            name='icon_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipegoods',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='icon_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
