# Generated by Django 4.2.13 on 2024-05-28 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gusto', '0003_alter_families_icon_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='icon_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default='Блюдо', max_length=255),
        ),
        migrations.AlterField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
