# Generated by Django 4.2.13 on 2024-05-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gusto', '0005_alter_families_icon_link_alter_families_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='families',
            options={'verbose_name': 'Семья', 'verbose_name_plural': 'Семьи'},
        ),
        migrations.AlterModelOptions(
            name='familygoodsinstock',
            options={'verbose_name': 'Продукт в наличии в семье', 'verbose_name_plural': 'Продукты в наличии в семье'},
        ),
        migrations.AlterModelOptions(
            name='familymembers',
            options={'verbose_name': 'Член семьи', 'verbose_name_plural': 'Члены семьи'},
        ),
        migrations.AlterModelOptions(
            name='familyrecipes',
            options={'verbose_name': 'Рецепт семьи', 'verbose_name_plural': 'Рецепты семьи'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'История заказов', 'verbose_name_plural': 'История заказов'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='recipegoods',
            options={'verbose_name': 'Продукт для рецепта', 'verbose_name_plural': 'Продукты для рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipesgroup',
            options={'verbose_name': 'Группа рецептов', 'verbose_name_plural': 'Группы рецептов'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
