# Generated by Django 4.2.13 on 2024-05-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gusto', '0008_remove_families_icon_link_remove_recipes_icon_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gusto.measure', verbose_name='Единица измерения'),
        ),
    ]
